version: '3'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ipsep
      - DOCKER_INFLUXDB_INIT_PASSWORD=ipsep2025
      - DOCKER_INFLUXDB_INIT_ORG=power_logic
      - DOCKER_INFLUXDB_INIT_BUCKET=mensualx6
      - DOCKER_INFLUXDB_INIT_RETENTION=180d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token_telegraf
    networks:
      - monitoring_net
    restart: unless-stopped

  influxdb-init:
    image: influxdb:2.7
    container_name: influxdb-init
    depends_on:
      - influxdb
    volumes:
      - ./init.sh:/init.sh:ro
    entrypoint: [ "sh", "/init.sh" ]
    networks:
      - monitoring_net

  telegraf:
    image: telegraf:1.34.4
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - monitoring_net

volumes:
  influxdb-data:

networks:
  monitoring_net:
    driver: bridge
