[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[inputs.modbus]]
  name = "PowerLogic4000_Warnings"
  controller = "tcp://modbus-sim:5020"
  timeout = "10s"
  slave_id = 1
  holding_registers = [
    { name = "voltaje",  byte_order = "AB", data_type = "UINT16", address = [0], scale = 0.1},
    { name = "current_l1",     byte_order = "AB", data_type = "UINT16", address = [3], scale = 0.1},
    { name = "active_power",   byte_order = "AB", data_type = "UINT16", address = [6], scale = 1.0}
  ]

# --- NUEVA SECCIÓN: Procesador Starlark para determinar la franja horaria ---
[[processors.starlark]]
  source = '''
def apply(metric):
    hour = metric.time.hour # Obtener la hora del timestamp de la métrica (hora local del Telegraf)

    # Definir las franjas horarias
    # Asegúrate que estas horas coincidan con las de config.yaml si las usas para umbrales
    if hour >= 8 and hour < 20: # 8am a 8pm
        metric.tags["franja_horaria"] = "DIA"
    else: # 8:01pm a 7:59am
        metric.tags["franja_horaria"] = "NOCHE"
    return metric
'''

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "token_telegraf"
  organization = "power_logic"
  bucket = "powerlogic_warnings_tmp"
