[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

[[inputs.modbus]]
  name = "PowerLogic4000_Warnings"
  controller = "tcp://modbus-sim:5020"
  timeout = "10s"
  slave_id = 1
  
  # --- LISTA DE REGISTROS CON NOMBRES ESTANDARIZADOS Y FINALES ---
  holding_registers = [
    { name = "voltaje_a_n",              byte_order = "AB", data_type = "UINT16", address = [0], scale = 0.1},
    { name = "corriente_a",              byte_order = "AB", data_type = "UINT16", address = [3], scale = 0.1},
    { name = "potencia_activa_total",    byte_order = "AB", data_type = "UINT16", address = [6], scale = 1.0},
    { name = "potencia_reactiva_total",  byte_order = "AB", data_type = "UINT16", address = [7], scale = 1.0},
    { name = "potencia_aparente_total",  byte_order = "AB", data_type = "UINT16", address = [8], scale = 1.0},
    { name = "frequency",                byte_order = "AB", data_type = "UINT16", address = [9], scale = 0.01}
  ]

# --- El procesador Starlark se mantiene igual, etiquetando todo lo que recibe ---
[[processors.starlark]]
  source = '''
def apply(metric):
    timestamp_ns = metric.time
    # Simplificamos el cálculo de la hora
    hour = (timestamp_ns // 3600000000000) % 24
    if hour >= 8 and hour < 20:
        metric.tags["franja_horaria"] = "DIA"
    else:
        metric.tags["franja_horaria"] = "NOCHE"
    return metric
'''

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "token_telegraf"
  organization = "power_logic"
  bucket = "powerlogic_warnings_tmp" # Bucket específico para las alertas
